from fastapi import APIRouter, Depends, Query, status
from sqlalchemy.orm import Session
from typing import List

from database import get_db
from models.user import User
from dependencies import get_current_user
from schemas.promotion import PromotionCreate, PromotionOut, PromotionPackageOut
from schemas.common import PaginatedResponse
from services.promotion_service import promotion_service

router = APIRouter(prefix="/promotions", tags=["Promotions"])

@router.get("/packages", response_model=List[PromotionPackageOut])
def list_promotion_packages(db: Session = Depends(get_db)):
    """List all active promotion packages."""
    return promotion_service.get_active_packages(db)

@router.post("", response_model=PromotionOut, status_code=status.HTTP_201_CREATED)
def create_promotion(
    data: PromotionCreate,
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Create a new promotion for an approved listing."""
    return promotion_service.create_promotion(db, current_user.id, data)

@router.get("/my", response_model=PaginatedResponse[PromotionOut])
def get_my_promotions(
    page: int = Query(1, ge=1),
    page_size: int = Query(20, ge=1, le=100),
    current_user: User = Depends(get_current_user),
    db: Session = Depends(get_db)
):
    """Get paginated promotions generated by the current user."""
    items, total = promotion_service.get_my_promotions(db, current_user.id, page, page_size)
    return PaginatedResponse.create(
        items=items,
        total=total,
        page=page,
        page_size=page_size
    )
